name: Build and deploy to hoster.by FTP

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build Delopro.sln --configuration Release

      - name: dotnet publish
        run: dotnet publish Delopro.sln -c Release -o ./publish

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./publish

  deploy-to-hoster-ftp:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Download publish artifact 
        uses: actions/download-artifact@v4 
        with: 
          name: .net-app
          path: ./publish
          
      - name: Create appsettings
        run: |
          $json = @"
          {
            "Logging": {
                "LogLevel": {
                    "Default": "Information",
                    "Microsoft.AspNetCore": "Warning"
                }
            },

            "OwnerNickname": "alex",
            "AdminNickname": "admin",
          }
          "@
          $json | Out-File -FilePath ./publish/appsettings.json -Encoding UTF8

      - name: Create appsettings Production
        run: |
          $json = @"
          {
            "ConnectionStrings": {
              "MssqlDeloproDb": "${{ secrets.MSSQL_DELOPRO_DB_CONNECTION_STRING }}"
            },

            "OwnerEmail": "airlex34@gmail.com",
            "ClientUrl": "https://www.delopro.site",
            
            "CorsOrigins": [
              "http://delopro.site",
              "http://www.delopro.site",
              "https://delopro.site",
              "https://www.delopro.site"
            ]

            "AesKey": "${{ secrets.AESKEY }}",
            "AesIV": "${{ secrets.AESIV }}",            
            
            "SmtpEmailSender": {
                "Host": "${{ secrets.SMTP_EMAIL_SENDER_HOST }}",
                "UserName": "${{ secrets.SMTP_EMAIL_SENDER_USERNAME }}",
                "Password": "${{ secrets.SMTP_EMAIL_SENDER_PASSWORD }}"
            },
            
            "DocsFolderName": "docs",
            
            "GoogleDrive": {
                "ApplicationName": "${{ secrets.GOOGLE_DRIVE_APPLICATION_NAME }}",
                "FolderId": "${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}",
                "Secrets": "${{ secrets.GOOGLE_DRIVE_SECRETS }}"
            }
          }
          "@
          $json | Out-File -FilePath ./publish/appsettings.Production.json -Encoding UTF8  

      - name: Upload files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_PATH }}
          local-dir: ./publish/
          protocol: ftp




